### PR TITLE
Combine arm64.Dockerfile and amd64.Dockerfile

### LINKED ISSUE #156: combine amd64.Dockerfile and arm64.Dockerfile
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

combine https://github.com/kubernetes-csi/csi-driver-smb/blob/master/pkg/smbplugin/amd64.Dockerfile and https://github.com/kubernetes-csi/csi-driver-smb/blob/master/pkg/smbplugin/arm64.Dockerfile as one Dockerfile, the only difference is base image.

/assign @mayankshah1607 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**
/kinds feature

**What this PR does / why we need it**:
Combine arm64.Dockerfile and amd64.Dockerfile as a single Dockerfile
- Use build arch `ARCH` to define which architecture to build for 
**Which issue(s) this PR fixes**:

Fixes #156

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
`Ubuntu E2E tests` action is using kind to deploy a cluster and then run e2e tests, I would still like to know why it failed. BTW, last time you hit blocking issue implementing nfs driver e2e tests on `kind`, what was the exact issue at that time? `kind` cluster was working at least in a period of time, then it's broken?

**Comment by mayankshah1607** [comment]
> Ubuntu E2E tests action is using kind to deploy a cluster and then run e2e tests, I would still like to know why it failed. BTW, last time you hit blocking issue implementing nfs driver e2e tests on kind, what was the exact issue at that time? kind cluster was working at least in a period of time, then it's broken?

@andyzhangx  NFS server was not working on KinD because it may have had issues with installing `nfs-kernel-server` on the nodes, which is a requirement to provision NFS storage. But that issue was specific to NFS provisioning.
It seems like the PVC is not able to move out of the `Pending` phase. It is a little hard to debug what is happening inside a KinD cluster on GH Actions, so even I am not sure what may be going wrong. 
Can we temporarily remove this? Any issues with having only **`pull-csi-driver-smb-e2e` prow job?

**Comment by andyzhangx** [comment]
ok, let's disable E2E tests in github action, thanks.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
