### PR TITLE
fix: deployment hangs

### PR DESCRIPTION
**Pull request by davhdavh**
<!--  Thanks for sending a pull request!  Here are some tips for you:

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Controller uses hostnetwork, so hangs because the new deployment can never acquire the ports it wants.

**Requirements**:
- [x] uses [conventional commit messages]

**Release note**:
```
Fix: Deployment of controller might hang due to inability to acquire port
```

### CODE REVIEW

**Comment by davhdavh** [comment]
and description lost here also?!?

/kind bug

**Release note**:
```
Fix: Deployment might hang on upgrade due to unable to acquire port
```

**Review by andyzhangx — COMMENTED** [review]
could you run `helm package charts/latest/csi-driver-smb -d charts/latest/` to update tgz file change?

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
