### PR TITLE
fix: add serviceAccount for driver daemonset running on the node

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
chore: add serviceAccount for driver daemonset running on the node
it's required on RedHat Openshift: https://github.com/kubernetes-csi/csi-driver-nfs/pull/334/files#r868940032

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: add serviceAccount for driver daemonset running on the node
```

### CODE REVIEW

**Comment by steveizzle** [comment]
hey @andyzhangx, when is the new release planned?

**Comment by andyzhangx** [comment]
> hey @andyzhangx, when is the new release planned, which includes this fix?

@steveizzle does this PR fix the issue on OpenShift?

**Comment by steveizzle** [comment]
> > hey @andyzhangx, when is the new release planned, which includes this fix?
> 
> @steveizzle does this PR fix the issue on OpenShift?

Honestly I don't know, but this helps also when using PSPs or something equivalent bound to service accounts

**Comment by andyzhangx** [comment]
> > > hey @andyzhangx, when is the new release planned, which includes this fix?
> > 
> > 
> > @steveizzle does this PR fix the issue on OpenShift?
> 
> Honestly I don't know, but this helps also when using PSPs or something equivalent bound to service accounts

@steveizzle ok, let me publish a new release this week.

**Pull request merged**
