### PR TITLE
make image.*.repository variables relative by default

### PR DESCRIPTION
**Pull request by amarkevich**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

`image.baseRepo` can be used to specify the registry once

**Which issue(s) this PR fixes**:

none

**Requirements**:

- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
what's the point of this PR? `baseRepo` setting is already supported by following logic, you only need to make the doc more clear.

https://github.com/kubernetes-csi/csi-driver-smb/blob/999ac2b1e391ff035f72aaa0e0a0f31efd1fecd4/charts/latest/csi-driver-smb/templates/csi-smb-controller.yaml#L56-L60

**Comment by amarkevich** [comment]
To use 'baseRepo' all the 'image.*.repository' values should be relative.
This PR change default values to be relative and configured using 'baseRepo' by default

**Comment by andyzhangx** [comment]
> To use 'baseRepo' all the 'image.*.repository' values should be relative. This PR change default values to be relative and configured using 'baseRepo' by default

@amarkevich this is already supported today

**Comment by amarkevich** [comment]
@andyzhangx now its not enough to set 'baseRepo' to switch image repository completely but all 'image.*.repository' values should be changed to be relative. This PR make it by default

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
