### PR TITLE
move integration tests into github workflows

### LINKED ISSUE #54: Move integration test in travis to test-infra
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

set up a few CI tests in test-infra, e.g.
 - pull-smb-csi-driver-unit 
 - pull-smb-csi-driver-verify
 - pull-smb-csi-driver-windows-build
 - pull-smb-csi-driver-integration
 - pull-smb-csi-driver-sanity

could put into 
https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-csi

and refer to https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/azurefile-csi-driver

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by boddumanohar**
**What type of PR is this?**
Currently 

/kind cleanup

**What this PR does / why we need it**:
Currently half of the tests are in GitHub workflows and few others in travis.yml. With this change, except e2e tests, everything else be moved to GitHub workflows. 

**Which issue(s) this PR fixes**:

Fixes #54

**Requirements**:
- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by boddumanohar** [comment]
Update: removed the integration tests from .travis.yml. Since these will run for Github workflows.

**Review by andyzhangx — COMMENTED** [review]
thanks for the contribution

**Comment by boddumanohar** [comment]
Update: 
1. Kept the changes in `.travis.yml` file.
2. moved all the integration test to `workflows/go.yml` file.
3. used `make smb-windows` command instead of plain command in `workflow/go.yml`. So that it will looks similar to the changes in `workflows/go.yml`.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
