### PR TITLE
test: Add unit tests

### PR DESCRIPTION
**Pull request by animeshk08**
This commit adds unit tests for csi-common,
mounter and smb.
A testMode parameter has been introduced in
server to enable running of unit tests.
Unit tests for unimplemented methods are also
added.

Signed-off-by: Animesh Kumar <animuz111@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation

> /kind failing-test
> /kind feature
> /kind flake
 
/kind test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
test: Add unit tests
```

### CODE REVIEW

**Comment by animeshk08** [comment]
Partially fixes: #12

**Comment by animeshk08** [comment]
Hi @andyzhangx. I have added all the unit-tests except for `smb/nodeserver.go`. I am trying to improve the tests for that file(mock the method calls) so that we don't need `sudo` while running the unit-tests. I will update the test once I am done.

Thanks!

**Comment by andyzhangx** [comment]
cc @Sakuralbj

**Pull request merged**
