### PR TITLE
feat: csi-proxy support in helm

### PR DESCRIPTION
**Pull request by davhdavh**
**What type of PR is this?**

/kind documentation
/kind feature
/kind api-change

**What this PR does / why we need it**:

Add support for the csi-proxy daemonset using host-process

**Release note**:
```
Helm chart can now install csi-proxy host-process daemonset on the windows nodes, eliminating the manual install step previously necessary.
```

### CODE REVIEW

**Comment by davhdavh** [comment]
I need a bit of help with that failing test. I dont understand what it is failing on that is related to my code?

 E0628 09:35:29.981213   10215 nodeserver.go:410] MakeDir failed on target: /home/prow/go/src/sigs.k8s.io/csi-driver-smb/pkg/smb/smb.go (mkdir /home/prow/go/src/sigs.k8s.io/csi-driver-smb/pkg/smb/smb.go: not a directory)

**Comment by davhdavh** [comment]
@andyzhangx Could you help with that failing test? I dont see how it is related to my changes

**Comment by andyzhangx** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-smb/635/pull-csi-driver-smb-verify/1674000758426570752
```
latest chart config has changed, pls run "helm package charts/latest/csi-driver-smb -d charts/latest/" to update tgz file
```

**Comment by davhdavh** [comment]
do you require anything else to merge?

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
