### PR TITLE
chore: repo rename

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
chore: repo rename

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@msau42 do you have permission to enable code coverage for this repo? thanks.
https://coveralls.io/github/kubernetes-csi/csi-driver-smb

Looks like I don't have the permission of kubernetes-csi org, can you enable it?

image

**Comment by andyzhangx** [comment]
```
The command "go test -covermode=count -coverprofile=profile.cov ./pkg/..." exited with 0.
5.42s$ $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
The command "$GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci" exited with 1.
```

**Comment by msau42** [comment]
Hm I don't seem to have permission either. Can we disable it for now, and follow up on enabling it separately?

**Pull request merged**
