### PR TITLE
Add tolerance to Windows node no schedule taint

### PR DESCRIPTION
**Pull request by lizhuqi**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Add tolerance to Windows node no schedule taint. DaemonSets targeting Windows must include an explicit toleration for the NoSchedule taint.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
we already use `nodeSelector` to match Windows node, why do we want to use taint in this PR?
https://github.com/kubernetes-csi/csi-driver-smb/blob/2d3ef8a858e5e9c0aeae0257de237ad817a9f600/deploy/csi-smb-node-windows.yaml#L16-L17

**Comment by lizhuqi** [comment]
I am adding the tolerance which will allow the pods to schedule onto nodes with NoSchedule taints. Node taints overrides nodeSelector. 

See this doc about taint and tolerance: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

Here is another good doc talking about how to control scheduling with node taints:
https://cloud.google.com/kubernetes-engine/docs/how-to/node-taints

**Comment by andyzhangx** [comment]
could you squash all commits into one, thanks

**Comment by lizhuqi** [comment]
I tried the command "git rebase -i HEAD~5" but it is not squashing into one......

**Comment by lizhuqi** [comment]
And in the middle I lost my real commit so have to manually added back so  only the latest commit has the real change.

**Comment by lizhuqi** [comment]
I think my local branch is kind of messed up. Can you set as Squash and merge mode when you review? Next PR I will try to squash before I push it.

**Comment by andyzhangx** [comment]
I did a modification on this PR to resolve conflict.

**Comment by lizhuqi** [comment]
Thanks Andy!!!

**Pull request merged**
