### PR TITLE
feat: add removeSMBMappingDuringUnmount config in chart config

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
feat: add removeSMBMappingDuringUnmount config in chart config
related to https://github.com/kubernetes-csi/csi-driver-smb/pull/505

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
feat: add removeSMBMappingDuringUnmount config in chart config
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
cc @vitaliy-leschenko

**Comment by vitaliy-leschenko** [comment]
Looks good. Maybe make sense to add the same option to `deploy/csi-smb-node-windows.yaml` for people who don't use helm?

**Comment by andyzhangx** [comment]
> Looks good. Maybe make sense to add the same option to `deploy/csi-smb-node-windows.yaml` for people who don't use helm?

@vitaliy-leschenko add in commit (https://github.com/kubernetes-csi/csi-driver-smb/pull/527/commits/05f916298311584a47142c53c6ddfc0c5ee2dd2a), thanks.

**Comment by vitaliy-leschenko** [comment]
@andyzhangx, Beautiful. This is more than I could wish for. When we can expect release 1.9.0?

**Comment by andyzhangx** [comment]
> @andyzhangx, Beautiful. This is more than I could wish for. When we can expect release 1.9.0?

@vitaliy-leschenko will release 1.9.0 this week.

**Pull request merged**
