### PR TITLE
Remove security context with "privileged: true" setting on Windows node

### PR DESCRIPTION
**Pull request by lizhuqi**
Remove security context with "privileged: true" setting 

DaemonSet in Windows node is not allowed to perform privileged actions so privileged field in security context shouldn't be true.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
        fix: Bug Fixes 🐞
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
Remove security context with "privileged: true" setting on Windows node
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
would you also remove the securityContext here? thanks.
https://github.com/kubernetes-csi/csi-driver-smb/blob/a9a2e47b1790b18e722e9d0b4d413c4e8a520507/deploy/csi-smb-node-windows.yaml#L98-L99

**Comment by lizhuqi** [comment]
My change will merge back to master so those two lines will be removed after the PR is merged I think. Do you mean make the changes to the other versions?

**Comment by andyzhangx** [comment]
> My change will merge back to master so those two lines will be removed after the PR is merged I think. Do you mean make the changes to the other versions?

sorry I meant this: 
https://github.com/kubernetes-csi/csi-driver-smb/blob/a9a2e47b1790b18e722e9d0b4d413c4e8a520507/charts/latest/csi-driver-smb/templates/csi-smb-node-windows.yaml#L100-L101

**Comment by andyzhangx** [comment]
could you squash all commits by `git rebase -i HEAD~4`? thanks.

**Comment by andyzhangx** [comment]
> could you squash all commits by `git rebase -i HEAD~4`? thanks.

not necessary now, I have set as `Squash and merge` mode.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by lizhuqi** [comment]
Thanks Andy for the approval!

**Pull request merged**
