### PR TITLE
feat: Storage class support

### LINKED ISSUE #60: provide storage class support
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

We could provide storage class support even it's static provisioning, and then this driver would pass storage parameters to `NodeStageVolume`

refer to https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//smb-server.default.svc.cluster.local/share"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
reclaimPolicy: Retain # can only support retain
volumeBindingMode: Immediate
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
feat: Storage class support

We could provide storage class support even it's static provisioning, and then this driver would pass storage parameters to `NodeStageVolume`

refer to https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//smb-server.default.svc.cluster.local/share"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
reclaimPolicy: Retain # can only support retain
volumeBindingMode: Immediate
```

**Which issue(s) this PR fixes**:

Fixes #60

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
feat: Storage class support
```

### CODE REVIEW

**Comment by msau42** [comment]
Do you really need to provide storageclass support for this? Couldn't you put these fields directly in the PV object?

**Comment by andyzhangx** [comment]
> Do you really need to provide storageclass support for this? Couldn't you put these fields directly in the PV object?

@msau42 
provide storage class support is another option, it's quite useful in helm charts, e.g.
```
helm install --set persistence.storageClass="smb" --set persistence.size=100Gi --generate-name bitnami/wordpress
```

**Comment by andyzhangx** [comment]
@msau42 also, I think for nfs driver, it has same requirement, e.g. https://github.com/kubernetes-csi/csi-driver-nfs/issues/30
I will try to provide "dynamic" provisioning for this smb driver, e.g. user brings own samba server, and this driver could provision a new folder under samba server in "dynamic" provisioning stage.

**Comment by msau42** [comment]
IIUC, the use case for implementing a no-op CreateVolume is to support Helm charts that only know how to create PVCs, instead of manually creating the PV?

**Comment by andyzhangx** [comment]
> IIUC, the use case for implementing a no-op CreateVolume is to support Helm charts that only know how to create PVCs, instead of manually creating the PV?

yes, by providing storage class support, we can use this driver in helm chart or other deployments

**Comment by msau42** [comment]
Ok, I would clarify that in the docs because that's not the usual expected behavior.

**Comment by andyzhangx** [comment]
> Ok, I would clarify that in the docs because that's not the usual expected behavior.

@msau42 thanks, will do.
Do you think I could port same functionality to nfs csi driver? https://github.com/kubernetes-csi/csi-driver-nfs/issues/30#issuecomment-614991049

**Comment by msau42** [comment]
I was thinking of actually having the CreateVolume mount the share to create the subdir, and then unmount it when done, but this would require the provisioner to run as privileged.

I'm not a big fan of not being able to support DeleteVolume, but if there are folks asking for this, we can consider it as a stop-gap solution.

**Pull request merged**
