### PR TITLE
feat: support pv/pvc metadata for subDir parameter

### LINKED ISSUE #502: Templated Share Subdirectory
**Is your feature request related to a problem?/Why is this needed**

We have a number of SMB NAS systems that we use as cluster-wide, general purpose storage, but provisioning sub-directories for each application is time-consuming and error prone and requires a human admin to configure. 

As of now, we have to define a csi-smb-provisioned StorageClass per application deployment just to reliably control the directory that an application stores it's data in which again requires another additional cluster-admin step. 

**Describe the solution you'd like in detail**
Ideally, a StorageClass could define a "subDir" template string that allows the admin to control how a new PVC is allocated a SMB share. 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-auto
provisioner: smb.csi.k8s.io
parameters:
  source: "//mynas.my.domain/storage/root"
  subDir: "smb-auto-${pvc.annotations['app.kubernetes.io/instance']}"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "storage"
```

Given the above as an example of suggested syntax, The following additional use cases should be taken into consideration: 

A unique share name per pvc:
Given: `subDir: "smb-auto-${pvc.metadata.name}"`
Result: `//mynas.my.domain/storage/root/smb-auto-pvc-95f1d979-9cb2-4a84-90ed-5d25cebeccc4` 

Namespace-specific shared storage:
Given:  `subDir: "smb-auto-${pvc.metadata.namespace}"` 
Result: `//mynas.my.domain/storage/root/smb-auto-production`

A shared storage share that multiple pods of the same deployment share 
Given: `subDir: "smb-auto-${pvc.annotations['app.kubernetes.io/instance']}"`
Result: `//mynas.my.domain/storage/root/smb-auto-nginx-frontend`

**Describe alternatives you've considered**
This feature request appears to be related to the discussion under issue #428 

**Additional context**
Kubernetes 1.23

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
feat: support pv/pvc metadata in subDir parameter

- `subDir` parameter supports following pv/pvc metadata transform
> if `subDir` value contains following string, it would transforms into corresponding pv/pvc name or namespace
 - `${pvc.metadata.name}`
 - `${pvc.metadata.namespace}`
 - `${pv.metadata.name}`

**Which issue(s) this PR fixes**:

Fixes #502

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
feat: support pv/pvc metadata in subDir parameter
```

### CODE REVIEW

**Comment by jingxu97** [comment]
@andyzhangx does it require any csi provisioner side of changes to support this feature? Is this a feature that is currently supported by any driver?

**Comment by andyzhangx** [comment]
> @andyzhangx does it require any csi provisioner side of changes to support this feature? Is this a feature that is currently supported by any driver?

@jingxu97 csi-provisioner already supports this by setting `- "--extra-create-metadata=true"`, this is a feature specific to CSI driver , so answer is No, it depends on specific CSI driver.

**Comment by ayuzzz** [comment]
Hi there, we are eagerly waiting for the fix to be available. Do you have a timeline for this to be released?

We tried to install the master version of csi-smb driver and got the following sub-directory name (placeholders not getting replaced by actual parameters from PVC.yml).

image

**Comment by andyzhangx** [comment]
> Hi there, we are eagerly waiting for the fix to be available. Do you have a timeline for this to be released?
> 
> We tried to install the master version of csi-smb driver and got the following sub-directory name (placeholders not getting replaced by actual parameters from PVC.yml).
> 
> image

@ayuzzz it's not merged, @jingxu97 could you approve? I think this is quite a useful feature.

**Comment by jingxu97** [comment]
is there e2e tests to validate the behavior including creation/deletion?

Could you also have an end to end example to show how this feature can be used?

**Comment by andyzhangx** [comment]
> is there e2e tests to validate the behavior including creation/deletion?
> 
> Could you also have an end to end example to show how this feature can be used?

@jingxu97 Yes,  such metadata is already added in e2e test:
`"subDir": "subDirectory-${pvc.metadata.name}",`

And example are already added to `driver-parameters.md` file, I think that's ok since it's special usage.

**Comment by andyzhangx** [comment]
@jingxu97 there is quite similar implementation on nfs driver, could you also approve? https://github.com/kubernetes-csi/csi-driver-nfs/pull/353 thanks.

**Comment by andyzhangx** [comment]
@ayuzzz pls try master branch with `gcr.io/k8s-staging-sig-storage/smbplugin:canary` image, let me know whether that works in your side, and then I would cut a new release.

**Pull request merged**
