### PR TITLE
cleanup: remove 1903 1909 2004 Windows image which is end of life

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
cleanup: remove 1903 1909 2004 Windows image which is end of life

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
cleanup: remove 1903 1909 2004 Windows image which is end of life
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@lizhuqi pull-csi-driver-smb-e2e-gce test is failing, would you take a look?

**Comment by lizhuqi** [comment]
> @lizhuqi pull-csi-driver-smb-e2e-gce test is failing, would you take a look?

Sure. I will take a look today.

**Comment by lizhuqi** [comment]
3 windows nodes failed to start because of the node set up failure

2021/12/10 11:34:49 GCEMetadataScripts: windows-startup-script-ps1: Exception caught in script:
2021/12/10 11:34:49 GCEMetadataScripts: windows-startup-script-ps1: At C:\k8s-node-setup.psm1:1308 char:5
2021/12/10 11:34:49 GCEMetadataScripts: windows-startup-script-ps1: +     Throw ("Timeout while waiting ${timeout} seconds for kubelet and  ...
2021/12/10 11:34:49 GCEMetadataScripts: windows-startup-script-ps1: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021/12/10 11:34:49 GCEMetadataScripts: windows-startup-script-ps1: Kubernetes Windows node setup failed: Timeout while waiting 10 seconds for kubelet and kube-proxy

**Pull request merged**
