### PR TITLE
chore: upgrade to csi-proxy-v1.0.1

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
chore: upgrade to csi-proxy-v1.0.1

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@lizhuqi would you fix the `pull-csi-driver-smb-e2e-gce` failure? this PR should not be related to the test failure.

**Comment by lizhuqi** [comment]
Only one test case is failing in pull-csi-driver-smb-e2e-gce now. Rerun to see if it was transient.

/test pull-csi-driver-smb-e2e-gce

**Comment by lizhuqi** [comment]
Return to see if the networking resources leaked is one-off
/test pull-csi-driver-smb-e2e-gce

**Comment by lizhuqi** [comment]
/lgtm

the leaking resource issue is caused by util failed to clean up firewalls.

**Pull request merged**
