### PR TITLE
fix: upgrade to debian 11.0 to fix vulnerability

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: upgrade to debian 11.0 to fix vulnerability

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
fix: upgrade to debian 11.0 to fix vulnerability
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
ubuntu site is down?
```
#5 0.980 Get:1 http://deb.debian.org/debian bullseye InRelease [113 kB]
#5 0.980 Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#5 5.246 Get:3 http://security.debian.org/debian-security bullseye-security/main arm64 Packages [36.5 kB]
#5 31.01 Err:1 http://deb.debian.org/debian bullseye InRelease
#5 31.01   Connection timed out [IP: 151.101.186.132 80]
#5 31.07 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#5 37.61 Get:5 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [2092 B]
#5 37.76 Fetched 122 kB in 37s (3295 B/s)
#5 37.76 Reading package lists...
#5 38.18 Building dependency tree...
#5 38.22 Reading state information...
#5 38.29 1 package can be upgraded. Run 'apt list --upgradable' to see it.
#5 38.29 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Connection timed out [IP: 151.101.186.132 80]
```

**Comment by andyzhangx** [comment]
the e2e test pod is running in google cloud, I think there is ubuntu site connection issue in google cloud. @lizhuqi

**Comment by lizhuqi** [comment]
GCP uses custom ubuntu images so maybe ubuntu site is blocked on purpose. Let me check this with our node team and get back to you tomorrow.

**Comment by andyzhangx** [comment]
> GCP uses custom ubuntu images so maybe ubuntu site is blocked on purpose. Let me check this with our node team and get back to you tomorrow.

@lizhuqi the ubuntu site connection issue only happened from yesterday

**Comment by lizhuqi** [comment]
> > GCP uses custom ubuntu images so maybe ubuntu site is blocked on purpose. Let me check this with our node team and get back to you tomorrow.
> 
> Julie Qi the ubuntu site connection issue only happened from yesterday

yeah, this is new, starting from Sep 22nd. Our guest OS team is investigating this issue now. I will keep you posted.  Please hold on this PR. Thanks!

**Comment by andyzhangx** [comment]
@lizhuqi there is still debian site connection timeout issue:
```
30.84 Err:1 http://security.debian.org/debian-security bullseye-security InRelease
#6 30.84   Connection timed out [IP: 151.101.2.132 80]
```

**Comment by andyzhangx** [comment]
related to this conversation: https://kubernetes.slack.com/archives/C09QZ4DQB/p1632710433059900?thread_ts=1632414457.031600&cid=C09QZ4DQB

**Comment by andyzhangx** [comment]
> related to this conversation: https://kubernetes.slack.com/archives/C09QZ4DQB/p1632710433059900?thread_ts=1632414457.031600&cid=C09QZ4DQB

@lizhuqi there must be some MTU config change in google cloud in around 9/22, I worked out a workaround in test-infra to fix this issue: https://github.com/kubernetes/test-infra/pull/23757

**Comment by lizhuqi** [comment]
> > related to this conversation: https://kubernetes.slack.com/archives/C09QZ4DQB/p1632710433059900?thread_ts=1632414457.031600&cid=C09QZ4DQB
> 
> Julie Qi there must be some MTU config change in google cloud in around 9/22, I worked out a workaround in test-infra to fix this issue: [kubernetes/test-infra#23757](https://github.com/kubernetes/test-infra/pull/23757)

Thanks Andy for sharing this! I will share this with our guest OS team as well.

**Comment by andyzhangx** [comment]
> > > related to this conversation: https://kubernetes.slack.com/archives/C09QZ4DQB/p1632710433059900?thread_ts=1632414457.031600&cid=C09QZ4DQB
> > 
> > 
> > Julie Qi there must be some MTU config change in google cloud in around 9/22, I worked out a workaround in test-infra to fix this issue: [kubernetes/test-infra#23757](https://github.com/kubernetes/test-infra/pull/23757)
> 
> Thanks Andy for sharing this! I will share this with our guest OS team as well.

@lizhuqi all k8s test-infra tests are impacted by this MTU config change, after the above PR merged, it still requires a few days to take effect. So if it could be reverted in google guest OS, that may be faster. Thanks.

**Comment by lizhuqi** [comment]
> > > > related to this conversation: https://kubernetes.slack.com/archives/C09QZ4DQB/p1632710433059900?thread_ts=1632414457.031600&cid=C09QZ4DQB
> > > 
> > > 
> > > Julie Qi there must be some MTU config change in google cloud in around 9/22, I worked out a workaround in test-infra to fix this issue: [kubernetes/test-infra#23757](https://github.com/kubernetes/test-infra/pull/23757)
> > 
> > 
> > Thanks Andy for sharing this! I will share this with our guest OS team as well.
> 
> Julie Qi all k8s test-infra tests are impacted by this MTU config change, after the above PR merged, it still requires a few days to take effect. So if it could be reverted in google guest OS, that may be faster. Thanks.

Yes, we have dev working on fixing this issue now.

**Comment by andyzhangx** [comment]
@lizhuqi  gce e2e test still failed? https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-smb/354/pull-csi-driver-smb-e2e-gce/1443011426837860352

**Comment by lizhuqi** [comment]
Network resource leaked issue is a known issue. This is why I disable the
flag in the job config in my test infra PR.

**Comment by lizhuqi** [comment]
> > > > > related to this conversation: https://kubernetes.slack.com/archives/C09QZ4DQB/p1632710433059900?thread_ts=1632414457.031600&cid=C09QZ4DQB
> > > > 
> > > > 
> > > > Julie Qi there must be some MTU config change in google cloud in around 9/22, I worked out a workaround in test-infra to fix this issue: [kubernetes/test-infra#23757](https://github.com/kubernetes/test-infra/pull/23757)
> > > 
> > > 
> > > Thanks Andy for sharing this! I will share this with our guest OS team as well.
> > 
> > 
> > Julie Qi all k8s test-infra tests are impacted by this MTU config change, after the above PR merged, it still requires a few days to take effect. So if it could be reverted in google guest OS, that may be faster. Thanks.
> 
> Yes, we have dev working on fixing this issue now.

The rollback is complete on google cloud side. So you no longer need that workaround.

**Pull request merged**
