### PR TITLE
CI: Use `golangci-lint-action` for running linters

### PR DESCRIPTION
**Pull request by mayankshah1607**
Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>

**What type of PR is this?**

**What this PR does / why we need it**:
CI: Use `golangci-lint-action` for running linters

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-csi/csi-driver-smb/issues/118

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by mayankshah1607** [comment]
@andyzhangx Added a separate action for running static checks. This runs the go linter

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
could you also port this PR to other CSI drivers: azuredisk, azurefile & blob drivers, thanks.

**Comment by mayankshah1607** [comment]
>could you also port this PR to other CSI drivers: azuredisk, azurefile & blob drivers, thanks.

On it! 👍

**Pull request merged**
