### PR TITLE
fix: windows image build error

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: windows image build error
This is a workaround fix, wait for buildkit fix on v0.8.0: https://github.com/moby/buildkit/pull/1879

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
fix: windows image build error
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
build ARM64 docker image failure:
```
#7 [3/4] RUN clean-install ca-certificates cifs-utils util-linux e2fsprogs ...
#7 0.269 /bin/sh: 0: Can't open clean-install
#7 ERROR: executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs]: exit code: 127
------
 > [3/4] RUN clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs:
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs]: exit code: 127
```

**Comment by andyzhangx** [comment]
@mayankshah1607 ARM64 image build is broken by this PR, feel free to modify the PR, thanks.

**Comment by andyzhangx** [comment]
@mayankshah1607 how did you fix it?

**Comment by mayankshah1607** [comment]
@andyzhangx It seemed like the tests were flaky. Re-running them seemed to do the job. The changes introduced in this PR doesn't seem to be affecting the Arm build process anyway, right?

**Pull request merged**
