### PR TITLE
chore: upgrade CSIDriver to v1 from v1beta1

### LINKED ISSUE #177: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

```console
$ curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/deploy/install-driver.sh | bash -s master --
Installing SMB CSI driver, version: master ...
serviceaccount/csi-smb-controller-sa created
clusterrole.rbac.authorization.k8s.io/smb-external-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/smb-csi-provisioner-binding created
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
csidriver.storage.k8s.io/smb.csi.k8s.io created
deployment.apps/csi-smb-controller created
daemonset.apps/csi-smb-node created
daemonset.apps/csi-smb-node-win created
SMB CSI driver installed successfully.
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by dr0pdb**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
upgrades CSIDriver to v1 from the deprecated v1beta1 api group

**Which issue(s) this PR fixes**:

Fixes #177 

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
N/A

**Release note**:
```
none
```

### CODE REVIEW

**Comment by dr0pdb** [comment]
```
#7 [3/4] RUN clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs
#7 sha256:e413fb7825707e78d8da96f36053cbfcb0d4125cd80a60236ba15507ec8b7e59
#7 0.326 /bin/sh: 0: Can't open clean-install
#7 ERROR: executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs]: exit code: 127
------
 > [3/4] RUN clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs:
------
```

**Comment by andyzhangx** [comment]
> ```
> #7 [3/4] RUN clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs
> #7 sha256:e413fb7825707e78d8da96f36053cbfcb0d4125cd80a60236ba15507ec8b7e59
> #7 0.326 /bin/sh: 0: Can't open clean-install
> #7 ERROR: executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs]: exit code: 127
> ------
>  > [3/4] RUN clean-install ca-certificates cifs-utils util-linux e2fsprogs mount udev xfsprogs:
> ------
> ```

this is a flacky test, I filed an issue here: https://github.com/kubernetes-csi/csi-driver-smb/issues/179, could you take a look later? thanks.

**Comment by dr0pdb** [comment]
sure, I'll take a look.

**Comment by andyzhangx** [comment]
the arm64 image build error should be fixed by https://github.com/kubernetes-csi/csi-driver-smb/pull/174

**Comment by dr0pdb** [comment]
@andyzhangx How to upgrade the Kubernetes version on e2e tests?

It is failing with
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
helm.go:81: [debug] unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
```

This is because `CSIDriver` object became GA in Kubernetes 1.18

It seems like e2e test runs Kubernetes 1.17.16

```
2020/12/25 09:04:34 e2e.go:474: Cluster nodes:
k8s-agentpool1-42488232-vmss000000   Ready   agent    44s   v1.17.16
k8s-agentpool1-42488232-vmss000001   Ready   agent    44s   v1.17.16
k8s-master-42488232-0                Ready   master   44s   v1.17.16
```

**Comment by andyzhangx** [comment]
> @andyzhangx How to upgrade the Kubernetes version on e2e tests?
> 
> It is failing with
> 
> ```
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
> helm.go:81: [debug] unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
> ```
> 
> This is because `CSIDriver` object became GA in Kubernetes 1.18
> 
> It seems like e2e test runs Kubernetes 1.17.16
> 
> ```
> 2020/12/25 09:04:34 e2e.go:474: Cluster nodes:
> k8s-agentpool1-42488232-vmss000000   Ready   agent    44s   v1.17.16
> k8s-agentpool1-42488232-vmss000001   Ready   agent    44s   v1.17.16
> k8s-master-42488232-0                Ready   master   44s   v1.17.16
> ```

thanks for the investigation, I think let's hold this PR for a few months since v1.17 is still supported now.

**Comment by dr0pdb** [comment]
sure.

/hold

**Comment by dr0pdb** [comment]
Same error.

```
helm.go:81: [debug] unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
```

Kubernetes version is still 1.17.16. We need version 1.18 or above
```
print out all nodes status ...
NAME                                 STATUS   ROLES    AGE     VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-agentpool1-42488232-vmss000000   Ready    agent    8m33s   v1.17.16   10.240.0.34    <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   containerd://1.3.9+azure
k8s-agentpool1-42488232-vmss000001   Ready    agent    8m33s   v1.17.16   10.240.0.65    <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   containerd://1.3.9+azure
k8s-master-42488232-0                Ready    master   8m33s   v1.17.16   10.255.255.5   <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   containerd://1.3.9+azure
======================================================================================
```

**Comment by andyzhangx** [comment]
> Same error.
> 
> ```
> helm.go:81: [debug] unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
> ```
> 
> Kubernetes version is still 1.17.16. We need version 1.18 or above
> 
> ```
> print out all nodes status ...
> NAME                                 STATUS   ROLES    AGE     VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
> k8s-agentpool1-42488232-vmss000000   Ready    agent    8m33s   v1.17.16   10.240.0.34    <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   containerd://1.3.9+azure
> k8s-agentpool1-42488232-vmss000001   Ready    agent    8m33s   v1.17.16   10.240.0.65    <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   containerd://1.3.9+azure
> k8s-master-42488232-0                Ready    master   8m33s   v1.17.16   10.255.255.5   <none>        Ubuntu 18.04.5 LTS   5.4.0-1032-azure   containerd://1.3.9+azure
> ======================================================================================
> ```

I just tried to test running integration test...

**Pull request closed without merging**
